In [1]:
import json 
import os

import pandas as pd
from collections import Counter

In [2]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

In [3]:
from config.paths import RAW_DATA_DIR, PROCESSED_DATA_DIR

In [4]:
dfs = {}

name_map = {
    "attack.json": "attack",
    "defence.json": "defence",
    "goalkeeper.json": "goalkeeper",
    "passing.json": "passing",
    "summary.json": "summary"
}

for file in os.listdir(RAW_DATA_DIR):
   with open(Path(RAW_DATA_DIR / file), encoding="utf-8") as f:
      
      data = json.load(f)
      results = data["results"]
      
      name = name_map.get(file, file)
      df = pd.DataFrame(results)

      dfs[name] = df


dfs.keys()

dict_keys(['attack', 'defence', 'goalkeeper', 'passing', 'summary'])

In [5]:
attack_df = dfs["attack"].copy()
defence_df = dfs["defence"].copy()
goalkeeper_df = dfs["goalkeeper"].copy()
passing_df = dfs["passing"].copy()
summary_df = dfs["summary"].copy()

In [6]:
attack_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   goals                     537 non-null    int64
 1   expectedGoals             444 non-null    float64
 2   bigChancesMissed          537 non-null    int64
 3   successfulDribbles        537 non-null    int64
 4   totalShots                537 non-null    int64
 5   goalConversionPercentage  537 non-null    float64
 6   rating                    537 non-null    float64
 7   player                    537 non-null    object
 8   team                      537 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 37.9+ KB

In [7]:
list(attack_df.columns)

['goals',
 'expectedGoals',
 'bigChancesMissed',
 'successfulDribbles',
 'totalShots',
 'goalConversionPercentage',
 'rating',
 'player',
 'team']

In [8]:
attack_df["player"][0]

{'name': 'Erling Haaland',
 'slug': 'erling-haaland',
 'userCount': 949544,
 'gender': 'M',
 'id': 839956,
 'fieldTranslations': {'nameTranslation': {'ar': 'إيرلينغ هالاند',
   'bn': 'এরলিং হালান্ড',
   'hi': 'एर्लिंग हालैंड'},
  'shortNameTranslation': {'ar': 'إ. هالاند',
   'bn': 'ই. হালান্ড',
   'hi': 'ई. हालैंड'}}}

In [9]:
attack_df.loc[attack_df["expectedGoals"].isna()]

,goals,expectedGoals,bigChancesMissed,successfulDribbles,totalShots,goalConversionPercentage,rating,player,team
280,0,NaN,0,0,0,0.0,7.57,"{'name': 'Max Weiss', 'slug': 'max-weiss', 'us...","{'name': 'Burnley', 'slug': 'burnley', 'sport'..."
283,0,NaN,0,1,0,0.0,7.18,"{'name': 'James Trafford', 'slug': 'james-traf...","{'name': 'Manchester City', 'slug': 'mancheste..."
284,0,NaN,0,0,0,0.0,7.10,"{'name': 'Walter Benítez', 'slug': 'walter-ben...","{'name': 'Crystal Palace', 'slug': 'crystal-pa..."
285,0,NaN,0,0,0,0.0,7.10,"{'name': 'Stefan Ortega', 'slug': 'stefan-orte...","{'name': 'Nottingham Forest', 'slug': 'notting..."
286,0,NaN,0,0,0,0.0,7.10,"{'name': 'Daniel Bentley', 'slug': 'daniel-ben...","{'name': 'Wolverhampton', 'slug': 'wolverhampt..."
...,...,...,...,...,...,...,...,...,...
532,0,NaN,0,0,0,0.0,5.80,"{'name': 'Emil Krafth', 'slug': 'emil-krafth',...","{'name': 'Newcastle United', 'slug': 'newcastl..."
533,0,NaN,0,0,0,0.0,0.00,"{'name': 'James Rowswell', 'slug': 'james-rosw...","{'name': 'Tottenham Hotspur', 'slug': 'tottenh..."
534,0,NaN,0,0,0,0.0,0.00,"{'name': 'Myles Peart-Harris', 'slug': 'myles-...","{'name': 'Brentford', 'slug': 'brentford', 'sp..."
535,0,NaN,0,0,0,0.0,0.00,"{'name': 'Nehemiah Oriola', 'slug': 'nehemiah-...","{'name': 'Brighton & Hove Albion', 'slug': 'br..."
536,0,NaN,0,0,0,0.0,0.00,"{'name': 'Joe Knight', 'slug': 'joe-knight', '...","{'name': 'Brighton & Hove Albion', 'slug': 'br..."

In [10]:
defence_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   tackles           537 non-null    int64
 1   interceptions     537 non-null    int64
 2   clearances        537 non-null    int64
 3   errorLeadToGoal   537 non-null    int64
 4   outfielderBlocks  537 non-null    int64
 5   rating            537 non-null    float64
 6   player            537 non-null    object
 7   team              537 non-null    object
dtypes: float64(1), int64(5), object(2)
memory usage: 33.7+ KB

In [11]:
list(defence_df.columns)

['tackles',
 'interceptions',
 'clearances',
 'errorLeadToGoal',
 'outfielderBlocks',
 'rating',
 'player',
 'team']

In [12]:
defence_df.head()

,tackles,interceptions,clearances,errorLeadToGoal,outfielderBlocks,rating,player,team
0,120,59,85,0,10,7.23,"{'name': 'James Garner', 'slug': 'james-garner...","{'name': 'Everton', 'slug': 'everton', 'sport'..."
1,110,30,58,0,12,7.02,"{'name': 'João Palhinha', 'slug': 'joao-palhin...","{'name': 'Tottenham Hotspur', 'slug': 'tottenh..."
2,107,36,45,1,6,6.77,"{'name': 'João Gomes', 'slug': 'joao-gomes', '...","{'name': 'Wolverhampton', 'slug': 'wolverhampt..."
3,104,41,49,0,16,7.34,"{'name': 'Elliot Anderson', 'slug': 'elliot-an...","{'name': 'Nottingham Forest', 'slug': 'notting..."
4,103,35,36,0,12,7.19,"{'name': 'Mateus Fernandes', 'slug': 'mateus-f...","{'name': 'West Ham United', 'slug': 'west-ham-..."

In [13]:
goalkeeper_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   saves                       40 non-null     int64
 1   cleanSheet                  40 non-null     int64
 2   penaltySave                 40 non-null     int64
 3   savedShotsFromInsideTheBox  40 non-null     int64
 4   runsOut                     40 non-null     int64
 5   rating                      40 non-null     float64
 6   player                      40 non-null     object
 7   team                        40 non-null     object
dtypes: float64(1), int64(5), object(2)
memory usage: 2.6+ KB

In [14]:
passing_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   bigChancesCreated         537 non-null    int64
 1   assists                   537 non-null    int64
 2   accuratePasses            537 non-null    int64
 3   accuratePassesPercentage  537 non-null    float64
 4   keyPasses                 537 non-null    int64
 5   rating                    537 non-null    float64
 6   player                    537 non-null    object
 7   team                      537 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 33.7+ KB

In [15]:
summary_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   goals                     537 non-null    int64
 1   expectedGoals             444 non-null    float64
 2   successfulDribbles        537 non-null    int64
 3   tackles                   537 non-null    int64
 4   assists                   537 non-null    int64
 5   accuratePassesPercentage  537 non-null    float64
 6   rating                    537 non-null    float64
 7   player                    537 non-null    object
 8   team                      537 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 37.9+ KB

In [16]:
list(goalkeeper_df.columns)

['saves',
 'cleanSheet',
 'penaltySave',
 'savedShotsFromInsideTheBox',
 'runsOut',
 'rating',
 'player',
 'team']

In [17]:
list(passing_df.columns)

['bigChancesCreated',
 'assists',
 'accuratePasses',
 'accuratePassesPercentage',
 'keyPasses',
 'rating',
 'player',
 'team']

In [18]:
list(summary_df.columns)

['goals',
 'expectedGoals',
 'successfulDribbles',
 'tackles',
 'assists',
 'accuratePassesPercentage',
 'rating',
 'player',
 'team']

### Processing DataFrame

In [19]:
def preprocess_dataframe(df):
    df.rename(columns={"rating": "sofascoreRating"}, inplace=True)
    # df["dfName"] = df.attrs["name"]

    df_player_normalized = pd.json_normalize(df["player"])
    df_player_normalized.rename(columns={"id": "playerId"}, inplace=True)
    df_player_normalized = df_player_normalized[["name", "playerId"]]

    df_team_normalized = pd.json_normalize(df["team"])
    df_team_normalized.rename(columns={"name": "teamName", "id": "teamId"}, inplace=True)
    df_team_normalized = df_team_normalized[["teamName", "teamId"]]

    df = pd.concat(
    [df.drop(["player", "team"], axis=1), 
     df_player_normalized, 
     df_team_normalized], 
     axis=1)
    
    return df

In [20]:
attack_df = preprocess_dataframe(attack_df)
defence_df = preprocess_dataframe(defence_df)
passing_df = preprocess_dataframe(passing_df)
goalkeeper_df = preprocess_dataframe(goalkeeper_df)
summary_df = preprocess_dataframe(summary_df)

In [21]:
attack_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   goals                     537 non-null    int64
 1   expectedGoals             444 non-null    float64
 2   bigChancesMissed          537 non-null    int64
 3   successfulDribbles        537 non-null    int64
 4   totalShots                537 non-null    int64
 5   goalConversionPercentage  537 non-null    float64
 6   sofascoreRating           537 non-null    float64
 7   name                      537 non-null    str
 8   playerId                  537 non-null    int64
 9   teamName                  537 non-null    str
 10  teamId                    537 non-null    int64
dtypes: float64(3), int64(6), str(2)
memory usage: 46.3 KB

In [22]:
defence_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   tackles           537 non-null    int64
 1   interceptions     537 non-null    int64
 2   clearances        537 non-null    int64
 3   errorLeadToGoal   537 non-null    int64
 4   outfielderBlocks  537 non-null    int64
 5   sofascoreRating   537 non-null    float64
 6   name              537 non-null    str
 7   playerId          537 non-null    int64
 8   teamName          537 non-null    str
 9   teamId            537 non-null    int64
dtypes: float64(1), int64(7), str(2)
memory usage: 42.1 KB

In [23]:
passing_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   bigChancesCreated         537 non-null    int64
 1   assists                   537 non-null    int64
 2   accuratePasses            537 non-null    int64
 3   accuratePassesPercentage  537 non-null    float64
 4   keyPasses                 537 non-null    int64
 5   sofascoreRating           537 non-null    float64
 6   name                      537 non-null    str
 7   playerId                  537 non-null    int64
 8   teamName                  537 non-null    str
 9   teamId                    537 non-null    int64
dtypes: float64(2), int64(6), str(2)
memory usage: 42.1 KB

In [24]:
goalkeeper_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   saves                       40 non-null     int64
 1   cleanSheet                  40 non-null     int64
 2   penaltySave                 40 non-null     int64
 3   savedShotsFromInsideTheBox  40 non-null     int64
 4   runsOut                     40 non-null     int64
 5   sofascoreRating             40 non-null     float64
 6   name                        40 non-null     str
 7   playerId                    40 non-null     int64
 8   teamName                    40 non-null     str
 9   teamId                      40 non-null     int64
dtypes: float64(1), int64(7), str(2)
memory usage: 3.3 KB

In [25]:
summary_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   goals                     537 non-null    int64
 1   expectedGoals             444 non-null    float64
 2   successfulDribbles        537 non-null    int64
 3   tackles                   537 non-null    int64
 4   assists                   537 non-null    int64
 5   accuratePassesPercentage  537 non-null    float64
 6   sofascoreRating           537 non-null    float64
 7   name                      537 non-null    str
 8   playerId                  537 non-null    int64
 9   teamName                  537 non-null    str
 10  teamId                    537 non-null    int64
dtypes: float64(3), int64(6), str(2)
memory usage: 46.3 KB

In [26]:
def add_col_suffix(df, suffix):
    new_col = []

    for col in df.columns:
        if col != "playerId":
            new_col.append(f"{col}_{suffix}")
        else:
            new_col.append(col)

    return new_col

In [27]:
attack_df.columns = add_col_suffix(attack_df, "attack")
defence_df.columns = add_col_suffix(defence_df, "defence")
passing_df.columns= add_col_suffix(passing_df, "passing")
goalkeeper_df.columns = add_col_suffix(goalkeeper_df, "goalkeeper")
summary_df.columns = add_col_suffix(summary_df, "summary")

In [28]:
from functools import reduce

dfs = [attack_df, defence_df, passing_df, goalkeeper_df, summary_df]
result_df = reduce(lambda left, right: pd.merge(left, right, on="playerId", how="outer"), dfs)
result_df

,goals_attack,expectedGoals_attack,bigChancesMissed_attack,successfulDribbles_attack,totalShots_attack,goalConversionPercentage_attack,sofascoreRating_attack,name_attack,playerId,teamName_attack,...,goals_summary,expectedGoals_summary,successfulDribbles_summary,tackles_summary,assists_summary,accuratePassesPercentage_summary,sofascoreRating_summary,name_summary,teamName_summary,teamId_summary
0,1,1.02,0,1,8,12.50,6.69,James Milner,791,Brighton & Hove Albion,...,1,1.02,1,15,1,86.86,6.69,James Milner,Brighton & Hove Albion,30
1,0,0.25,1,1,2,0.00,6.43,Ashley Barnes,27028,Burnley,...,0,0.25,1,0,0,30.77,6.43,Ashley Barnes,Burnley,6
2,13,12.44,11,11,56,23.21,6.68,Danny Welbeck,33902,Brighton & Hove Albion,...,13,12.44,11,24,1,79.42,6.68,Danny Welbeck,Brighton & Hove Albion,30
3,0,NaN,0,0,0,0.00,6.98,Martin Dúbravka,42209,Burnley,...,0,NaN,0,1,0,58.22,6.98,Martin Dúbravka,Burnley,6
4,1,0.33,0,3,6,16.67,6.80,Jordan Henderson,42694,Brentford,...,1,0.33,3,27,3,77.89,6.80,Jordan Henderson,Brentford,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,1,1.18,0,6,6,16.67,6.77,Max Dowman,1917626,Arsenal,...,1,1.18,6,2,0,88.46,6.77,Max Dowman,Arsenal,42
533,0,NaN,0,0,0,0.00,6.45,Joel Drakes-Thomas,2007717,Crystal Palace,...,0,NaN,0,1,0,72.73,6.45,Joel Drakes-Thomas,Crystal Palace,7
534,0,NaN,0,0,0,0.00,6.30,Ben Winterburn,2007889,Bournemouth,...,0,NaN,0,0,0,0.00,6.30,Ben Winterburn,Bournemouth,60
535,0,NaN,0,2,0,0.00,6.70,Jocelin Ta Bi,2138729,Sunderland,...,0,NaN,2,1,0,100.00,6.70,Jocelin Ta Bi,Sunderland,41
536,0,NaN,0,0,0,0.00,6.80,Jerome Abbey,2263877,Wolverhampton,...,0,NaN,0,1,0,20.00,6.80,Jerome Abbey,Wolverhampton,3

In [29]:
nominated_players = [
    "Bruno Fernandes",
    "Gabriel Magalhães",
    "Morgan Gibbs-White",
    "Erling Haaland",
    "David Raya",
    "Declan Rice",
    "Antoine Semenyo",
    "Igor Thiago"
]

In [30]:
nominated_df = result_df[result_df["name_summary"].apply(lambda x: x.strip()).isin(nominated_players)]

In [31]:
nominated_df

,goals_attack,expectedGoals_attack,bigChancesMissed_attack,successfulDribbles_attack,totalShots_attack,goalConversionPercentage_attack,sofascoreRating_attack,name_attack,playerId,teamName_attack,...,goals_summary,expectedGoals_summary,successfulDribbles_summary,tackles_summary,assists_summary,accuratePassesPercentage_summary,sofascoreRating_summary,name_summary,teamName_summary,teamId_summary
70,9,10.83,8,15,85,10.59,7.61,Bruno Fernandes,288205,Manchester United,...,9,10.83,15,54,21,82.20,7.61,Bruno Fernandes,Manchester United,35
105,0,NaN,0,1,0,0.00,6.90,David Raya,581310,Arsenal,...,0,NaN,1,1,0,64.80,6.90,David Raya,Arsenal,42
174,27,25.43,30,17,126,21.43,7.31,Erling Haaland,839956,Manchester City,...,27,25.43,17,15,8,65.63,7.31,Erling Haaland,Manchester City,17
204,4,3.17,3,14,40,10.00,7.46,Declan Rice,856714,Arsenal,...,4,3.17,14,70,5,87.31,7.46,Declan Rice,Arsenal,42
216,15,10.84,10,30,83,18.07,6.92,Morgan Gibbs-White,865912,Nottingham Forest,...,15,10.84,30,20,4,81.13,6.92,Morgan Gibbs-White,Nottingham Forest,14
224,3,2.93,4,1,27,11.11,7.27,Gabriel Magalhães,869792,Arsenal,...,3,2.93,1,38,4,88.17,7.27,Gabriel Magalhães,Arsenal,42
287,17,11.09,7,59,83,20.48,7.02,Antoine Semenyo,934354,Manchester City,...,17,11.09,59,45,4,80.02,7.02,Antoine Semenyo,Manchester City,17
388,22,20.57,20,29,84,26.19,6.92,Igor Thiago,1016907,Brentford,...,22,20.57,29,38,1,69.21,6.92,Igor Thiago,Brentford,50

### Data Clearning

In [32]:
col_names = nominated_df.columns

In [33]:
base_cols = Counter([col.rsplit("_")[0] for col in nominated_df.columns])

duplicate_cols = [col for col, num in base_cols.items() if num > 1]
duplicate_cols

['goals',
 'expectedGoals',
 'successfulDribbles',
 'sofascoreRating',
 'name',
 'teamName',
 'teamId',
 'tackles',
 'assists',
 'accuratePassesPercentage']

In [34]:
for base in duplicate_cols:
    matches = [col for col in nominated_df.columns if col.rsplit("_", 1)[0] == base]
    print(f"{base}: {matches}")

goals: ['goals_attack', 'goals_summary']
expectedGoals: ['expectedGoals_attack', 'expectedGoals_summary']
successfulDribbles: ['successfulDribbles_attack', 'successfulDribbles_summary']
sofascoreRating: ['sofascoreRating_attack', 'sofascoreRating_defence', 'sofascoreRating_passing', 'sofascoreRating_goalkeeper', 'sofascoreRating_summary']
name: ['name_attack', 'name_defence', 'name_passing', 'name_goalkeeper', 'name_summary']
teamName: ['teamName_attack', 'teamName_defence', 'teamName_passing', 'teamName_goalkeeper', 'teamName_summary']
teamId: ['teamId_attack', 'teamId_defence', 'teamId_passing', 'teamId_goalkeeper', 'teamId_summary']
tackles: ['tackles_defence', 'tackles_summary']
assists: ['assists_passing', 'assists_summary']
accuratePassesPercentage: ['accuratePassesPercentage_passing', 'accuratePassesPercentage_summary']

In [35]:
col_to_drop = [col for col in nominated_df.columns if col.rsplit("_", 1)[0] in duplicate_cols and not col.endswith("_summary")]

col_to_drop

['goals_attack',
 'expectedGoals_attack',
 'successfulDribbles_attack',
 'sofascoreRating_attack',
 'name_attack',
 'teamName_attack',
 'teamId_attack',
 'tackles_defence',
 'sofascoreRating_defence',
 'name_defence',
 'teamName_defence',
 'teamId_defence',
 'assists_passing',
 'accuratePassesPercentage_passing',
 'sofascoreRating_passing',
 'name_passing',
 'teamName_passing',
 'teamId_passing',
 'sofascoreRating_goalkeeper',
 'name_goalkeeper',
 'teamName_goalkeeper',
 'teamId_goalkeeper']

In [36]:
nominated_df = nominated_df.drop(columns=col_to_drop)

In [37]:
nominated_df = nominated_df.drop(columns="teamId_summary")

In [38]:
nominated_df.set_index("playerId", inplace=True)

In [39]:
nominated_df.columns = [col.rsplit("_", 1)[0] for col in nominated_df.columns]

In [40]:
nominated_df.loc[934354, "teamName"] = "Bournemouth / Manchester City"

In [41]:
nominated_df

,bigChancesMissed,totalShots,goalConversionPercentage,interceptions,clearances,errorLeadToGoal,outfielderBlocks,bigChancesCreated,accuratePasses,keyPasses,...,runsOut,goals,expectedGoals,successfulDribbles,tackles,assists,accuratePassesPercentage,sofascoreRating,name,teamName
playerId,,,,,,,,,,,,,,,,,,,,,
288205,8,85,10.59,20,42,0,5,33,1639,137,...,NaN,9,10.83,15,54,21,82.20,7.61,Bruno Fernandes,Manchester United
581310,0,0,0.00,1,37,1,0,0,707,3,...,32.0,0,NaN,1,1,0,64.80,6.90,David Raya,Arsenal
839956,30,126,21.43,5,42,0,1,9,252,25,...,NaN,27,25.43,17,15,8,65.63,7.31,Erling Haaland,Manchester City
856714,3,40,10.00,37,78,1,12,17,1865,64,...,NaN,4,3.17,14,70,5,87.31,7.46,Declan Rice,Arsenal
865912,10,83,18.07,13,32,1,3,5,980,49,...,NaN,15,10.84,30,20,4,81.13,6.92,Morgan Gibbs-White,Nottingham Forest
869792,4,27,11.11,23,182,1,34,5,1528,7,...,NaN,3,2.93,1,38,4,88.17,7.27,Gabriel Magalhães,Arsenal
934354,7,83,20.48,13,29,0,7,8,749,39,...,NaN,17,11.09,59,45,4,80.02,7.02,Antoine Semenyo,Bournemouth / Manchester City
1016907,20,84,26.19,12,64,0,8,6,436,24,...,NaN,22,20.57,29,38,1,69.21,6.92,Igor Thiago,Brentford

In [42]:
potm_wins = {
    "Bruno Fernandes": 1,      # March 2026
    "Gabriel Magalhães": 0,
    "Morgan Gibbs-White": 1,   # April 2026
    "Erling Haaland": 1,       # September 2025
    "David Raya": 0,
    "Declan Rice": 0,
    "Antoine Semenyo": 1,      # February 2026
    "Igor Thiago": 2,          # November 2025 & January 2026
}

player_position = {
    "Bruno Fernandes": "Midfielder",
    "Gabriel Magalhães": "Defender",
    "Morgan Gibbs-White": "Midfielder",   
    "Erling Haaland": "Attacker",     
    "David Raya": "Goalkeeper",
    "Declan Rice": "Midfielder",
    "Antoine Semenyo": "Attacker",    
    "Igor Thiago": "Attacker",         
}

potm_df = pd.DataFrame({
    "name": list(potm_wins.keys()),
    "potm_wins": list(potm_wins.values()),
    "position": list(player_position.values())
})

In [43]:
nominated_df = nominated_df.reset_index().merge(potm_df, on="name", how="left").set_index("playerId")

In [44]:
nominated_df

,bigChancesMissed,totalShots,goalConversionPercentage,interceptions,clearances,errorLeadToGoal,outfielderBlocks,bigChancesCreated,accuratePasses,keyPasses,...,expectedGoals,successfulDribbles,tackles,assists,accuratePassesPercentage,sofascoreRating,name,teamName,potm_wins,position
playerId,,,,,,,,,,,,,,,,,,,,,
288205,8,85,10.59,20,42,0,5,33,1639,137,...,10.83,15,54,21,82.20,7.61,Bruno Fernandes,Manchester United,1,Midfielder
581310,0,0,0.00,1,37,1,0,0,707,3,...,NaN,1,1,0,64.80,6.90,David Raya,Arsenal,0,Goalkeeper
839956,30,126,21.43,5,42,0,1,9,252,25,...,25.43,17,15,8,65.63,7.31,Erling Haaland,Manchester City,1,Attacker
856714,3,40,10.00,37,78,1,12,17,1865,64,...,3.17,14,70,5,87.31,7.46,Declan Rice,Arsenal,0,Midfielder
865912,10,83,18.07,13,32,1,3,5,980,49,...,10.84,30,20,4,81.13,6.92,Morgan Gibbs-White,Nottingham Forest,1,Midfielder
869792,4,27,11.11,23,182,1,34,5,1528,7,...,2.93,1,38,4,88.17,7.27,Gabriel Magalhães,Arsenal,0,Defender
934354,7,83,20.48,13,29,0,7,8,749,39,...,11.09,59,45,4,80.02,7.02,Antoine Semenyo,Bournemouth / Manchester City,1,Attacker
1016907,20,84,26.19,12,64,0,8,6,436,24,...,20.57,29,38,1,69.21,6.92,Igor Thiago,Brentford,2,Attacker

In [45]:
nominated_df.to_csv(Path(PROCESSED_DATA_DIR / "pl_2025_26_nominees_stats.csv"), index=True)